### ISSUE TITLE
Demo instance send the same item repeatedly

### ISSUE THREAD

**Issue by fengkx** [fengkx/NodeRSSBot#1662]
I am facing similar issue like #1537

```
{"level":"error","message":{"error":"KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?\n    at Client_PG.acquireConnection (/app/node_modules/knex/lib/client.js:332:26)\n    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:305:28)\n    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)\n    at async updateFeed (/app/dist/source/proxies/rss-feed.js:169:16)\n    at async fetch (/app/dist/source/utils/fetch.js:128:9)\n    at async /app/dist/source/utils/fetch.js:153:24","type":"db"},"timestamp":"2024-06-26T02:25:31.830Z"}
```

this error show up a lot of times recently. Need more investigation.

**Comment by fengkx** [comment]
```
{"level":"error","message":{"error":"Error: SASL: Last message was not SASLResponse\n    at Object.finalizeSession (/app/node_modules/pg/lib/crypto/sasl.js:62:11)\n    at Client._handleAuthSASLFinal (/app/node_modules/pg/lib/client.js:281:12)\n    at /app/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)","type":"db"},"timestamp":"2024-06-26T03:03:55.371Z"}
```
another issue

**Comment by fengkx** [comment]
1. `Error: SASL: Last message was not SASLRespons` is related to [supabase](https://github.com/brianc/node-postgres/issues/3222).  Restart supabase project seem to solve the problem.

2. Downgrade pg from 8.12.0 to 8.11.x seem to solve the `KnexTimeoutError `

**Comment by fengkx** [comment]
> * `Error: SASL: Last message was not SASLRespons` is related to [supabase](https://github.com/brianc/node-postgres/issues/3222).  Restart supabase project seem to solve the problem.
> * Downgrade pg from 8.12.0 to 8.11.x seem to solve the `KnexTimeoutError `

After switch back to supabse direct connection instead of supavisor, both 1 and 2 resolved.
