### ISSUE TITLE
Some feed url contain `{`, `"` which can not fit in JavaScript template string and HTML

### ISSUE THREAD

**Issue by fengkx** [fengkx/NodeRSSBot#186]
example https://www.apkmirror.com/apk/huawei/huawei-fm-radio/variant-%7B%22minapi_slug%22%3A%22minapi-28%22%7D/feed/
```plain
https://www.apkmirror.com/apk/huawei/huawei-fm-radio/variant-{"minapi_slug"%3A"minapi-28"}/feed/
```

```js
error: Error: 400: Bad Request: can't parse entities: Expected equal sign in declaration of an attribute of the tag "a" at byte offset 3647
    at /root/NodeRSSBot/node_modules/telegraf/core/network/client.js:281:17
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async /root/NodeRSSBot/dist/source/utils/two-key-reply.js:10:9
    at async viewAll (/root/NodeRSSBot/dist/source/controlers/rss.js:148:5)
    at async /root/NodeRSSBot/dist/source/index.js:141:5
    at async exports.default (/root/NodeRSSBot/dist/source/middlewares/only-private-chat.js:13:5)
    at async exports.default (/root/NodeRSSBot/dist/source/middlewares/send-error.js:36:9)
    at async Promise.all (index 0) {"timestamp":"2020-05-01T15:10:55.703Z"}
```

**Comment by fengkx** [comment]
```plain
This feed does not validate.

    line 25, column 124: Invalid character in a URI: https://www.apkmirror.com/apk/huawei/huawei-fm-radio/variant-{"minapi_slug":"minapi-28"}/feed/ [help]

        ... ariant-{"minapi_slug":"minapi-28"}/feed/</link>
```
https://validator.w3.org/feed/check.cgi show url should be encoded in link tag of item. So we can output the url of item directly without encode it.

But I store unencoded URL in database. Because urldecode is an idempotent operation. We should encode the url before we send it in html href attribute.

**Comment by fengkx** [comment]
Fixed https://github.com/fengkx/NodeRSSBot/releases/tag/v0.6.1
