### ISSUE TITLE
Heroku error 

### ISSUE THREAD

**Issue by bnsave100** [fengkx/NodeRSSBot#377]
2021-03-24T17:59:45.151675+00:00 app[worker.1]: 

2021-03-24T17:59:45.151705+00:00 app[worker.1]: > noderssbot@0.10.0 start

2021-03-24T17:59:45.151706+00:00 app[worker.1]: > cross-env NODE_PRODUTION=true node dist/source/index.js

2021-03-24T17:59:45.151707+00:00 app[worker.1]: 

2021-03-24T17:59:46.028302+00:00 app[worker.1]: {"message":"Database is located in postgres://udpterdvhpcriv:5555606f74703e55b4db5c63a82101d25a036c197d7e88164224946ea0f56ad7@ec2-54-158-222-248.compute-1.amazonaws.com:5432/d2ai8ubefs4pab","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-03-24T17:59:46.023Z"}

2021-03-24T17:59:46.029710+00:00 app[worker.1]: {"message":"Using Default language is en","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-03-24T17:59:46.029Z"}

2021-03-24T17:59:46.030296+00:00 app[worker.1]: {"message":"send the latest 5 items for each feed","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-03-24T17:59:46.029Z"}

2021-03-24T17:59:46.031107+00:00 app[worker.1]: {"message":"NodeRSSBot is ready","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-03-24T17:59:46.030Z"}

2021-03-24T17:59:46.159262+00:00 app[worker.1]: /app/node_modules/pg-protocol/dist/parser.js:278

2021-03-24T17:59:46.159270+00:00 app[worker.1]:             : new messages_1.DatabaseError(messageValue, length, name);

2021-03-24T17:59:46.159271+00:00 app[worker.1]:               ^

2021-03-24T17:59:46.159272+00:00 app[worker.1]: 

2021-03-24T17:59:46.159272+00:00 app[worker.1]: error: no pg_hba.conf entry for host "34.229.41.212", user "udpterdvhpcriv", database "d2ai8ubefs4pab", SSL off

2021-03-24T17:59:46.159274+00:00 app[worker.1]:     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:278:15)

2021-03-24T17:59:46.159274+00:00 app[worker.1]:     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)

2021-03-24T17:59:46.159275+00:00 app[worker.1]:     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)

2021-03-24T17:59:46.159275+00:00 app[worker.1]:     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:10:42)

2021-03-24T17:59:46.159276+00:00 app[worker.1]:     at Socket.emit (node:events:369:20)

2021-03-24T17:59:46.159277+00:00 app[worker.1]:     at addChunk (node:internal/streams/readable:313:12)

2021-03-24T17:59:46.159277+00:00 app[worker.1]:     at readableAddChunk (node:internal/streams/readable:288:9)

2021-03-24T17:59:46.159277+00:00 app[worker.1]:     at Socket.Readable.push (node:internal/streams/readable:227:10)

2021-03-24T17:59:46.159278+00:00 app[worker.1]:     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {

2021-03-24T17:59:46.159278+00:00 app[worker.1]:   length: 167,

2021-03-24T17:59:46.159279+00:00 app[worker.1]:   severity: 'FATAL',

2021-03-24T17:59:46.159280+00:00 app[worker.1]:   code: '28000',

2021-03-24T17:59:46.159280+00:00 app[worker.1]:   detail: undefined,

2021-03-24T17:59:46.159280+00:00 app[worker.1]:   hint: undefined,

2021-03-24T17:59:46.159281+00:00 app[worker.1]:   position: undefined,

2021-03-24T17:59:46.159281+00:00 app[worker.1]:   internalPosition: undefined,

2021-03-24T17:59:46.159282+00:00 app[worker.1]:   internalQuery: undefined,

2021-03-24T17:59:46.159282+00:00 app[worker.1]:   where: undefined,

2021-03-24T17:59:46.159282+00:00 app[worker.1]:   schema: undefined,

2021-03-24T17:59:46.159283+00:00 app[worker.1]:   table: undefined,

2021-03-24T17:59:46.159283+00:00 app[worker.1]:   column: undefined,

2021-03-24T17:59:46.159283+00:00 app[worker.1]:   dataType: undefined,

2021-03-24T17:59:46.159284+00:00 app[worker.1]:   constraint: undefined,

2021-03-24T17:59:46.159284+00:00 app[worker.1]:   file: 'auth.c',

2021-03-24T17:59:46.159284+00:00 app[worker.1]:   line: '502',

2021-03-24T17:59:46.159285+00:00 app[worker.1]:   routine: 'ClientAuthentication'

2021-03-24T17:59:46.159285+00:00 app[worker.1]: }

2021-03-24T17:59:46.223571+00:00 app[worker.1]: npm ERR! code 1

2021-03-24T17:59:46.224207+00:00 app[worker.1]: npm ERR! path /app

2021-03-24T17:59:46.231335+00:00 app[worker.1]: npm ERR! command failed

2021-03-24T17:59:46.231660+00:00 app[worker.1]: npm ERR! command sh -c cross-env NODE_PRODUTION=true node dist/source/index.js

2021-03-24T17:59:46.245942+00:00 app[worker.1]: 

2021-03-24T17:59:46.246129+00:00 app[worker.1]: npm ERR! A complete log of this run can be found in:

2021-03-24T17:59:46.246284+00:00 app[worker.1]: npm ERR!     /app/.npm/_logs/2021-03-24T17_59_46_232Z-debug.log

2021-03-24T17:59:46.294236+00:00 heroku[worker.1]: Process exited with status 1

2021-03-24T17:59:46.357703+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by fengkx** [comment]
#363
