### ISSUE TITLE
critical error in docker (any image newer than 092ebb)

### ISSUE THREAD

**Issue by Rongronggg9** [fengkx/NodeRSSBot#550]
# Any image newer than 50f7ce
**Demo or Self hosted**

-   [ ] Demo
-   [x] Self hosted

**Describe the bug**
Got a critical error (`cross-env not found`) that make the bot completely fail to start when running in docker, using any image newer than 50f7ce (50f7ced5645d1cdc3a441ddefe1a19e88658a6dc, included):
```
> noderssbot@0.10.1 start-withsnapshot
> cross-env NODE_PRODUTION=true node --heapsnapshot-signal=SIGUSR2 dist/source/index.js

sh: cross-env: not found
```

**To Reproduce**
```sh
docker run --name rssbot -d -v /var/data:/app/data/ -e RSSBOT_TOKEN=123456:abcdef123456-U fengkx/rssbot
```

**Expected behavior**
Dep `cross-env` should exist and not lead to a critical error.

**Screenshots / Logs**
See above.

# Any image newer than 092ebb but older than 50f7ce
**Demo or Self hosted**

-   [ ] Demo
-   [x] Self hosted

**Describe the bug**
Got a critical error (`Cannot find module 'fastq'`) that make the bot fail to initialize when running in docker, using any image newer than 092ebb (092ebb0b638aa45b898f3e04ac7a919065cf8603, included) but older than 50f7ce (50f7ced5645d1cdc3a441ddefe1a19e88658a6dc, not included):
```
{"message":"Migrate schema to latest version","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-10-13T17:22:54.351Z"}
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'fastq'
Require stack:
- /app/dist/source/utils/fetch.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/app/dist/source/utils/fetch.js:28:33)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/dist/source/utils/fetch.js' ]
}
{"message":"child process exit","code":1,"signal":null,"level":"\u001b[31merror\u001b[39m","timestamp":"2021-10-13T17:22:54.642Z"}
```

**To Reproduce**
```sh
docker run --name rssbot -d -v /var/data:/app/data/ -e RSSBOT_TOKEN=123456:abcdef123456-U fengkx/rssbot:092ebb
```

**Expected behavior**
Dep `fastq` should exist and not lead to a critical error.

**Screenshots / Logs**
<details>

```
> noderssbot@0.10.1 start-withsnapshot /app
> cross-env NODE_PRODUTION=true node --heapsnapshot-signal=SIGUSR2 dist/source/index.js

{"message":"sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).","level":"\u001b[33mwarn\u001b[39m","timestamp":"2021-10-13T17:22:54.075Z"}
{"message":"Database is located in /app/data/database.db","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-10-13T17:22:54.245Z"}
{"message":"Using Default language is zh-cn","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-10-13T17:22:54.246Z"}
{"message":"send the latest 10 items for each feed","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-10-13T17:22:54.249Z"}
{"message":"NodeRSSBot is ready","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-10-13T17:22:54.249Z"}
{"message":"Migrate schema to latest version","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-10-13T17:22:54.351Z"}
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'fastq'
Require stack:
- /app/dist/source/utils/fetch.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/app/dist/source/utils/fetch.js:28:33)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/dist/source/utils/fetch.js' ]
}
{"message":"child process exit","code":1,"signal":null,"level":"\u001b[31merror\u001b[39m","timestamp":"2021-10-13T17:22:54.642Z"}
{"message":"Migrate schema to latest version","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-10-13T17:22:54.647Z"}
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'fastq'
Require stack:
- /app/dist/source/utils/fetch.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/app/dist/source/utils/fetch.js:28:33)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/dist/source/utils/fetch.js' ]
}
{"message":"child process exit","code":1,"signal":null,"level":"\u001b[31merror\u001b[39m","timestamp":"2021-10-13T17:22:54.896Z"}
{"message":"Migrate schema to latest version","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-10-13T17:22:54.900Z"}
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'fastq'
Require stack:
- /app/dist/source/utils/fetch.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/app/dist/source/utils/fetch.js:28:33)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/dist/source/utils/fetch.js' ]
}
{"message":"child process exit","code":1,"signal":null,"level":"\u001b[31merror\u001b[39m","timestamp":"2021-10-13T17:22:55.159Z"}
{"message":"Migrate schema to latest version","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-10-13T17:22:55.163Z"}
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'fastq'
Require stack:
- /app/dist/source/utils/fetch.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/app/dist/source/utils/fetch.js:28:33)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/dist/source/utils/fetch.js' ]
}
{"message":"child process exit","code":1,"signal":null,"level":"\u001b[31merror\u001b[39m","timestamp":"2021-10-13T17:22:55.405Z"}
{"message":"Migrate schema to latest version","level":"\u001b[32minfo\u001b[39m","timestamp":"2021-10-13T17:22:55.411Z"}
{"message":"fetch process exit too much(3) times","level":"\u001b[31merror\u001b[39m","timestamp":"2021-10-13T17:22:55.473Z"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! noderssbot@0.10.1 start-withsnapshot: `cross-env NODE_PRODUTION=true node --heapsnapshot-signal=SIGUSR2 dist/source/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the noderssbot@0.10.1 start-withsnapshot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-13T17_22_56_062Z-debug.log
```

</details>

**Comment by fengkx** [comment]
Thanks for reporting, Fixed in 05acb07
