### ISSUE TITLE
Docker image error: standard_init_linux.go:211

### ISSUE THREAD

**Issue by DrNion** [fengkx/NodeRSSBot#74]
The docker logs says:
standard_init_linux.go:211: exec user process caused "exec format error"

I'm running it on a RaspberryPi with raspbian stretch

My container I created:
$ docker run --name rssbot --restart unless-stopped -d -v /ho
me/pi/telepot/noderssbot/data:/app/data/ -e RSSBOT_TOKEN=(my token) -e RSSBOT_LANG=en fengkx/node_rssbot

That's basically it, I hope there is a solution for me.
The noderssbot is my first docker "project" I dealed with so I might not see any obvious problems/solutions.

**Comment by fengkx** [comment]
The pre-build image is based on amd64 arch. And RaspberryPi is using arm. So there is no way to use pre-build image on it. It might work normally by building a docker image on your pi. Try to build a image using the following Dockerfile.

```Dockerfile
FROM arm32v7/node:12.12-alpine
WORKDIR /app
RUN apk add --no-cache --update build-base 
COPY . /app
ENV NODE_PRODUTION true
RUN npm install --production 
ENTRYPOINT npm run start

```

If your pi is using arm64 try [this](https://hub.docker.com/r/arm64v8/node/)

Please leave a comment if the issue is resolved(or not).

**Comment by DrNion** [comment]
Indeed it's armv71,
OK thanks I'll try that as soon as possible and post my results.

**Comment by DrNion** [comment]
So after `$ docker build .` everything went ok until I got errors during the node-pre-gyp installation-phase.

I installed node-gyp v6.0.0 and node-pre-gyp v0.13.0 manually with npm but I got the same error again.
(`node-pre-gyp -v` showed just the correct version in the dir where I git cloned the NodeRSSBot repository, is that normal?)
Python 2.7 is installed and should be up to date.

Even though I got those errors, I created the container using [--platform=linux/armv71](https://github.com/moby/moby/issues/36552) to distinguish between arm32v7 and armv71 (was that necessary?).

At the end of the day  `docker container logs <image id>` doesn't show me any error but I do not get any respons on Telegram either.


Here the node-pre-gyp error:
```
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v72-linux-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.1.0 and node@12.12.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python 2.7.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:303:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:132:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:175:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:267:16)
gyp ERR! stack     at exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:314:5)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Linux 4.19.66-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/app/node_modules/sqlite3/lib/binding/node-v72-linux-arm" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /app/node_modules/sqlite3
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/app/node_modules/sqlite3/lib/binding/node-v72-linux-arm --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 4.19.66-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /app/node_modules/sqlite3
node-pre-gyp ERR! node -v v12.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/app/node_modules/sqlite3/lib/binding/node-v72-linux-arm --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-20T13_41_59_844Z-debug.log
The command '/bin/sh -c npm install --production' returned a non-zero code: 1
```

**Comment by fengkx** [comment]
@DrNion try install python in the Dockerfile
```Dockerfile
RUN apk add --no-cache --update build-base python2
```
may work

**Comment by DrNion** [comment]
Yes now it worked, I still got a bunch of red code during the installation (again from node-pre-gyp and now quite a lot from sqlite3) but nothing from python.

After creating the container I got finally a response in telegram.

The /sub works but I cannot subscribe with the channel ID. 
`Unable to parse the url`

I'll tell you about the functionality of incoming subs after a little while.

**Comment by fengkx** [comment]
@DrNion Could you please paste the output here. Remember to set the bot as channel admin before you subscribe a feed for your channel.

**Comment by DrNion** [comment]
The Bot actually works fine, I got already my first feeds.

I'll send you the beginning of the code from where the errors started during the docker building (they were written in red so I guess those were errors) but those red codes reached my history limit of 2000 lines in putty and I couldn't copy the rest of it.

I may have understood why the URL of the channel-ID cannot be parsed.
The ID of private channels starts with a `-100` and the dash interferes with the @ symbol so it's not recognized anymore as an url. 
Deleting the dash makes it recognizable but then it says that the channel doesn't exist.
It may work though with public channels but I didn't try it yet and to be honest I'd prefere not to :)
Maybe it's a thing to create another Issue?

Here the output:
```
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v72-linux-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.1.0 and node@12.12.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
make: Entering directory '/app/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3280000/sqlite3.o
Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c: In function 'strftimeFunc':
Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c:14137:27: warning: cast between incompatible function types from 'int (*)(void *)' to 'void (*)(void *)' [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
                           ^
Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c:22052:52: note: in expansion of macro 'SQLITE_DYNAMIC'
                       z==zBuf ? SQLITE_TRANSIENT : SQLITE_DYNAMIC);
                                                    ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c: In function 'sqlite3ErrorWithMsg':
Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c:14137:27: warning: cast between incompatible function types from 'int (*)(void *)' to 'void (*)(void *)' [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
                           ^
Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c:30393:54: note: in expansion of macro 'SQLITE_DYNAMIC'
     sqlite3ValueSetStr(db->pErr, -1, z, SQLITE_UTF8, SQLITE_DYNAMIC);
                                                      ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c: In function 'sqlite3VdbeMemSetStr':
Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c:14137:27: warning: cast between incompatible function types from 'int (*)(void *)' to 'void (*)(void *)' [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
                           ^
Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c:75499:15: note: in expansion of macro 'SQLITE_DYNAMIC'
     if( xDel==SQLITE_DYNAMIC ){
               ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c: In function 'valueFromExpr':
Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c:14137:27: warning: cast between incompatible function types from 'int (*)(void *)' to 'void (*)(void *)' [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
```

**Comment by fengkx** [comment]
The output is the compile time output of SQLite. It is normal. Good to hear that. Are you using arm32v7?

**Comment by DrNion** [comment]
armv71 but I wrote arm32v7 into the dockerfile and it works so I guess those are the same, thanks for the help!

About the channel-ID which cannot be parsed what would you say?
Is there anything I can do?

**Comment by fengkx** [comment]
@DrNion Would you like to share the channel id to me here or by email(If you don't want it into public)?

Are there any information in logs/error.log?

**Comment by DrNion** [comment]
Ha I finally added some feeds to a specific private channel.

So let me explain what I found out :) 

There are two types of channels: private and public.
The private channel-ID starts every time with `-100` while the public channel-ID with the `@` symbole.
So as an example: `-1001234567890` or `@randomchat`.

Adding the private channel doesn't work via `/sub` since the `-100xxxxxx` isn't recognised as an URL.
But I added it with `/import`! 
I just uploaded `-1001234567890.opml` (without `@` since it is a private channel-ID) and voilà! It worked.

So your bot works perfectly fine on my pi.

The only thing what you could do if you want to (I'll use the `/import` function anyways so it's not necessary for me) is to implement the possibility to add also private channel-ID with `/sub`.

**Comment by fengkx** [comment]
Already fix in latest commit 6c57cc1a3fa3228e0520c3a3295c04c004f91679 638f7395bc4f587f475eed0617fb5ac9895bffb7

Have a try

**Comment by fengkx** [comment]
@DrNion Cloud you please post the complete Dockerfile tested on your pi here?

**Comment by DrNion** [comment]
Here it is. 
```
FROM arm32v7/node:12.12-alpine
WORKDIR /app
RUN apk add --no-cache --update build-base python2
COPY . /app
ENV NODE_PRODUTION true
RUN npm install --production
ENTRYPOINT npm run start
```

**Comment by DrNion** [comment]
OK now it parses also private channel-IDs. 

Thanks mate!
