### ISSUE TITLE
最新版本heroku部署报错

### ISSUE THREAD

**Issue by Silentely** [fengkx/NodeRSSBot#783]
一键Heroku部署后报错

log

2022-05-11T10:39:07.782724+00:00 app[worker.1]:       at Object.fetch (node:internal/deps/undici/undici:6372:20)  
2022-05-11T10:39:07.782725+00:00 app[worker.1]:       at fetch (node:internal/bootstrap/pre_execution:199:25)  
2022-05-11T10:39:07.782725+00:00 app[worker.1]:       at /app/node_modules/camaro/dist/camaro.js:22:251  
2022-05-11T10:39:07.782725+00:00 app[worker.1]:       at f.asm (/app/node_modules/camaro/dist/camaro.js:22:465)  
2022-05-11T10:39:07.782725+00:00 app[worker.1]:       at /app/node_modules/camaro/dist/camaro.js:92:220 {  
2022-05-11T10:39:07.782725+00:00 app[worker.1]:     input: '/app/node_modules/camaro/dist/camaro.wasm',  
2022-05-11T10:39:07.782726+00:00 app[worker.1]:     code: 'ERR_INVALID_URL'  
2022-05-11T10:39:07.782726+00:00 app[worker.1]:   }  
2022-05-11T10:39:07.782727+00:00 app[worker.1]: }  
2022-05-11T10:39:14.053572+00:00 app[worker.1]: {"level":"\u001b[32minfo\u001b[39m","message":"heapUsedBefore:  
 16766784 heapUsedAfter: 15879880 rssBefore: 123301888 rssAfater: 123301888 costed 25821137","timestamp":"2022-05-11T10:39:14.052Z"}

机器人提示抓取错误

**Comment by fengkx** [comment]
Pending: https://github.com/emscripten-core/emscripten/issues/16913

Add `--no-experimental-fetch` to the `NODE_OPTIONS` environment variable as a temporary soultaion
